www/config/routes.rb
Www::Application.routes.draw do

    

    get "home/index"

    resources :signin_or_signups

    resources :shipping_infos
    resources :make_a_choices

    get "sessions/new"
    get "cart/new"
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :product_categories do
        resources :products
    end
    resources :users do
        resources :carts
    end
    resources :users do
        resources :shipping_infos
    end
    resources :carts

    
    resources :product_providers

    get '/main',                  :to => 'product_categories#index'
    get '/signin',                :to => 'sessions#new'
    get '/signout',               :to => 'sessions#destroy'
    get '/signup',                :to => 'users#new'
    post '/add_product/:id',       :to => 'carts#new'
    post '/delete_product/:id',    :to => 'carts#destroy'
    get '/signup_step2',          :to => 'shipping_infos#new'
    get '/cart',                  :to => 'carts#show'
    get '/make_a_choice',         :to => 'make_a_choices#index'
    get '/update_qnt',            :to => 'carts#update' 

    root :to => "home#index"

end

www/app/models/cart.rb
class Cart < ActiveRecord::Base
  
    belongs_to  :user
    has_many    :cart_products
    has_many    :products, through: :cart_products
    
 
end

www/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
=begin
  В начале проверяется залогинен пользователь или нет. Если не залогинен, то выводится корзина гостя,
  которая хранится в куки. Если мы залогинены, то проверяем есть ли у нас корзина, соранная гостем.
  Естестественно если нет, то мы выводим с базы. Если все же у нас 2 корзины(в базе и в куки), то тут 
  есть 2 варианта: 
    1) товары в них совпадают. В этом случае сохраняем корзину с базы и выводим ее.
    2) товары в них разные. Тут мы отправляем юзера на страницу выбора между двумя корзинами.
       И в зависимости от выбора сохраняем ту или иную корзину.
=end

  # GET /cart
  def show
    # залогинен?
    if signed_in?                                       
      @user = current_user
      # есть ли корзина, собранная гостем?
      if !cookies[:cart_id].nil?                        
        @cart = current_user.cart                       
        @cart_cookies = cart_from_cookies
        # если товары в корзинах (с базы и с куки) совпадают                                      
        if (@cart.products.count != 0) && (@cart.products == @cart_cookies.products)               
          # то выводим только с базы
          current_user.cart = @cart                   
          find_cart_product(@cart)                    
          cookies.delete(:cart_id)                    
        else
          # иначе предлагаем сделать выбор
          case (params[:options])                     
          when "1"
            @cart = current_user.cart                 
            current_user.cart = @cart                                  
            find_cart_product(@cart)
            cookies.delete(:cart_id)                  
          when "2"
            @cart = cart_from_cookies                  
            current_user.cart = @cart            
            find_cart_product(@cart)
            cookies.delete(:cart_id)
          when nil                                    
            redirect_to "/make_a_choice"              
          end
        end
      else
        # выводим с базы
        @cart = current_user.cart                       
        find_cart_product(@cart)                        
      end
    else
      # выводим с куки
      @cart = cart_from_cookies                         
      find_cart_product(@cart)                          
    end

    
  end

  # POST /add_product
  def new
    # если залогинены, берем корзину из базы
    if signed_in?
      cart = current_user.cart
    else
      # если нет кук - создаем новую корзину
      if cookies[:cart_id].nil?
        cart = Cart.create
        cookies.signed[:cart_id] = cart.id

      # есть куки - берем корзину из кук
      else
        cart = cart_from_cookies
      end
    end   

    # добавляем товар в корзину 
    # или увеличиваем количество на 1, если он уже там
    product = cart.cart_products.find_by_product_id params[:id]
    if product
      product.update_attribute :quantity, product.quantity + 1
    else
      CartProduct.create product_id: params[:id], cart_id: cart.id, quantity: 1
    end      
    redirect_to "/cart" 
  end

  def update
    # достаем корзину
    cart = signed_in? ? current_user.cart : cart_from_cookies
    # просматриваем товары
    params[:product].each do |id, state|
      # удаляем отмеченные
      if !state[:deleted].nil?
        cart.cart_products.find_by_product_id(id).destroy
        next
      end

      # обновляем количество, если изменено
      if state[:updated_qty] != state[:initial_qty]
        cart.cart_products.find_by_product_id(id).update_attribute :quantity, state[:updated_qty]
      end
    end

    redirect_to "/cart"
  end
end
 

www/app/helpers/carts_helper.rb
module CartsHelper

	def find_cart_product(cart)
	    @cart = cart
	    @cart_products = @cart.cart_products.order('created_at').includes :product
	end

	def cart_from_cookies
	    Cart.find cookies.signed[:cart_id]
	end

end

www/app/views/carts/_form.html.slim
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

www/app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
'|
= link_to 'Back', carts_path

www/app/views/carts/index.html.slim
h1 Listing carts

h4 o0ps!

www/app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

www/app/views/carts/show.html.slim
javascript:
    // запрос сборщику
    var request;

    // сборщик через вебсокет
    function sendRequest() {
        $('#shipping_method').html('<img src="/assets/circular_progress_bar.gif" /><span />');
        var socket = new WebSocket("ws://localhost:8888/load_shipping_methods");

        socket.onopen = function() { 
            console.log("Соединение установлено");
            socket.send(JSON.stringify(request));
        };

        socket.onclose = function(event) { 
            if (event.wasClean) {
                console.log('Соединение закрыто чисто');
            } else {
                console.log('Обрыв соединения'); // например, "убит" процесс сервера
            }
            console.log('Код: ' + event.code + ' причина: ' + event.reason);
        };
         
        socket.onmessage = function(event) {
            console.log("Получены данные " + event.data);
            var message = JSON.parse(event.data);

            switch (message.type) {
                case "info":
                    $('#shipping_method span').text(message.data);
                    break;

                case "result":
                    switch (message.status) {
                        case "success":
                            var shipping_methods = JSON.parse(unescape(message.data));
                            var table = $('<table class="table table-striped"><thead><td>Способ доставки</td><td>Стоимость</td><td>Отслеживание посылки</td></thead><tbody /></table>');

                            var tbody = $('tbody', table);
                            for (var i in shipping_methods) {
                                var shipping_method = shipping_methods[i];
                                var tr = $('<tr/>');
                                tr.append($('<td>' + shipping_method.name + '</td>'));
                                tr.append($('<td>' + shipping_method.cost + ' руб.</td>'));
                                tr.append($('<td>' + (shipping_method.tracking == '1' ? '+' : '-') + '</td>'));
                                table.append(tr);
                            }
                            $('#shipping_method').html(table);
                            break;

                        case "error":
                            $('#shipping_method').html('<span class="label label-important">Произошла ошибка при загрузке способов доставки</span><br>' + message.data);
                            break;
                    }
                    break;
            }
            
        };

        socket.onerror = function(error) { 
            console.log("Ошибка " + error.message); 
        };
    }
    // для кнопки "Продолжить покупки"
    function back(product_id, category_id){
    document.location.href = "/product_categories/"+category_id+"/products/"+product_id;
    }        
    // Модальное окно "Рассчитать способы доставки"
    function modal(){
    $('#modal').modal({backdrop:false});
    }
    // Модальное окно "Вход или регистрация"
    function modal2(){ 
    $('#modal2').modal({backdrop:false});
    $('#modal2').css({  
        "width" : 700,   // ширина окна, px  
        "height" : 400 });  // высота окна, px
    }
    
    $(document).ready(function() {
        // Включение/отключение всех чекбоксов
        $("#delete_all").click(function() {
            var checked = $("#delete_all").attr("checked") || false;
            $(".delete_product").attr("checked", checked);
        });
    });

    
p#notice = notice
- if signed_in?
    h4 
        = "Корзина пользователя "
        = link_to current_user.email, current_user
- else 
    h4 Корзина гостя

/--------------------------------------------------

br
- if @cart.products.count == 0
    p.text-info
        h5
            | Уважаемый покупатель!
            | К сожалению, в настоящее время Ваша корзина пуста. 
- else
    br
    table class="table  table-bordered table-condensed info"
        tr bgcolor="#E6E6FA" 
            th width="300px"  
                p align="center"
                    | Название
            th width="100px" 
                p align="center"
                    | Количество
            th width="100px" 
                p align="center"
                    | Цена
            th width="100px" 
                p align="center"
                    | Сумма
            th width="100px" 
                form
                    p align="center"
                        | Убрать 
                        input type="checkbox" id="delete_all"
                     

    form action="/update_qnt" 
        - total_cost = 0
        - cart_info = ''
        - @cart_products.each do |cart_product|
            - id = cart_product.product.id
            - category = cart_product.product.product_categories.last.id
            - image_src = cart_product.product.image_src
            - price = cart_product.product.price
            - quantity = cart_product.quantity
            - ext_id = cart_product.product.ext_id
            - limitation  = cart_product.product.limitation
            - stock = cart_product.product.stock
            - product_provider_id = cart_product.product.product_provider_id 
            - cart_info += "#{ext_id}:{id:#{id}, ext_id:'#{ext_id}', category:#{category}, price:#{price}, qty:#{quantity}, stock:'#{stock}', limitation:'#{limitation}'},"
            
            /.row-fluid
            table class="table table-bordered table-condensed"
                tr.cart_product
                    /.span3
                    td width="40px"
                        p class="fig"
                            a onclick='back(#{id}, #{category})'
                                = image_tag cart_product.product.image_src, width: 50 

                    td width="250px"
                        a onclick='back(#{id}, #{category})'
                            = cart_product.product.name

                    /.span1
                    td width="100px"
                        p align="center"
                            input type="hidden" value="#{quantity}" name="product[#{id}][initial_qty]"
                            input type="number" value="#{quantity}" min=1 name="product[#{id}][updated_qty]" class="input-mini"
                            input type="hidden" value="#{ext_id}" name="product[#{id}][ext_id]"
                            input type="hidden" value="#{limitation}" name="product[#{id}][limitation]"
                            input type="hidden" value="#{stock}" name="product[#{id}][limitation]"
                            

                    /.span2
                    td width="100px"
                        p.text-info align="right"
                            - currency_course = BigDecimal($redis.hget("provider:#{product_provider_id}", "currency_course"))
                            - current_price = (price * currency_course).round
                            = current_price.to_s + " руб."

                    /.span2
                    td width="100px"
                        p.text-info align="right"
                            =  (current_price * quantity).to_s + " руб."
                            - total_cost += (current_price * quantity)

                    /.span2
                    td  width="100px"
                        p align="center"
                            input type="checkbox" name="product[#{id}][deleted]" class="delete_product"



        - if signed_in?
            - user_id = current_user.id
            - email = current_user.email
            - role = current_user.role
            - balance = current_user.balance
            - cart = current_user.cart.id
            - user_info = "id:#{user_id}, email:'#{email}', role:'#{role}', balance:'#{balance}'"

        - else
            - cart = Cart.find(cookies.signed[:cart_id]).id
            - user_info = "cart_id:#{cart}"

        // сбор информации
        script
            = "request = {cart_id: #{cart}, content: {#{cart_info}}, address: {#{user_info}}}"

        
        -if @cart.products.count != 0
            table class="table table-bordered table-condensed info"
                tr bgcolor="#E6E6FA"
                    td width="500px" 
                        button type="submit" id="update" class="btn" Применить
                        
                        // проверяется залогинен или нет. если да, то происходит расчет. если нет,
                        // то предлагается войти/зарегаться

                        -if signed_in?
                            button type="button" class="btn" onclick="sendRequest(), modal()" Рассчитать способы доставки
                        -else
                            button type="button" class="btn" onclick="modal2()" Рассчитать способы доставки
                        
                        - @cart_products = @cart.cart_products.order('updated_at').includes :product
                        - scr_category_id = @cart_products.last.product.product_categories.last.id
                        - src_product_id = @cart_products.last.product_id

                        button type="button" onclick='back(#{src_product_id}, #{scr_category_id})' class="btn" Продолжить покупки
   
                    td width="200px" 
                        span class="label label-info nav"
                            | ВСЕГО К ОПЛАТЕ:
                        span class=" nav pull-right"
                            p.text-info align="right"
                                = total_cost.to_s + " р"  
    

    // Модальные окна

    div id="modal" class="modal hide fade in" style="display: none;"
        div class="modal-header"
            a class="close" data-dismiss="modal" ×
            h2 Расчет способов доставки
        
        div class="modal-body"
            #shipping_method
        
        div class="modal-footer"
            a href="#" class="btn" data-dismiss="modal" Закрыть

    
    div id="modal2" class="modal hide fade in" style="display: none;"
        div class="modal-header"
            a class="close" data-dismiss="modal" ×
            h2 Войдите или зарегистрируйтесь

        div class="modal-body"
            .container-fluid
                .row-fluid
                    .span6
                        .well
                            h5 Зарегистрированный покупатель
                            br
                            = simple_form_for(:session, :url => sessions_path) do |f| 

                                = f.input :email, placeholder: 'Email', label: false, input_html: {type: 'text'}
                                = f.input :password, placeholder: 'Пароль', label: false
                                = f.button :submit, 'Войти'


                    .span6
                        .well
                            h5 Новый покупатель
                            br
                            form action="/signup" method="post"
                                button type="submit" class="btn" Зарегистрироваться
                                input type="hidden" value="1" name="hidden_flag"
                            br
                            br       