www/config/routes.rb
Www::Application.routes.draw do

    

    get "home/index"

    resources :signin_or_signups

    resources :shipping_infos
    resources :make_a_choices

    get "sessions/new"
    get "cart/new"
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :product_categories do
        resources :products
    end
    resources :users do
        resources :carts
    end
    resources :users do
        resources :shipping_infos
    end
    resources :carts

    
    resources :product_providers

    get '/main',                  :to => 'product_categories#index'
    get '/signin',                :to => 'sessions#new'
    get '/signout',               :to => 'sessions#destroy'
    get '/signup',                :to => 'users#new'
    post '/add_product/:id',       :to => 'carts#new'
    post '/delete_product/:id',    :to => 'carts#destroy'
    get '/signup_step2',          :to => 'shipping_infos#new'
    get '/cart',                  :to => 'carts#show'
    get '/make_a_choice',         :to => 'make_a_choices#index'
    get '/update_qnt',            :to => 'carts#update' 

    root :to => "home#index"

end

www/app/models/shipping_info.rb
class ShippingInfo < ActiveRecord::Base
  
  belongs_to      :user
=begin
  attr_accessible :first_name
  attr_accessible :user_id
  attr_accessible :last_name
  attr_accessible :address
  attr_accessible :city
  attr_accessible :state
  attr_accessible :country
  attr_accessible :post_code
  attr_accessible :phone
=end

  validates :first_name,  :presence => true, 
                          :length => { :within => 2..40 }
                   
  validates :last_name,   :presence => true, 
                          :length => { :within => 2..40 }

  validates :address,     :presence => true, 
                          :length => { :within => 2..40 }

  validates :city,        :presence => true, 
                          :length => { :within => 2..40 }

  validates :state,       :presence => true, 
                          :length => { :within => 2..40 }

  validates :country,     :presence => true, 
                          :length => { :within => 2..40 }

  validates :post_code,   :presence => true, 
                          :length => { :within => 5..6 },
                          :numericality => { :only_integer => true }

  validates :phone,       :presence => true, 
                          :length => { :within => 6..40 },
                          :numericality => true       

end

www/app/controllers/shipping_infos_controller.rb
class ShippingInfosController < ApplicationController
  # GET /shipping_infos
  # GET /shipping_infos.json
  def index
    @user = User.find params[:user_id]
    @shipping_info = @user.shipping_info
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shipping_infos }
    end
  end

  # GET /shipping_infos/1
  # GET /shipping_infos/1.json
  def show
    @shipping_info = ShippingInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipping_info }
    end
  end

  # GET /shipping_infos/new
  # GET /shipping_infos/new.json
  def new
    @shipping_info = ShippingInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shipping_info }
    end
  end

  # GET /shipping_infos/1/edit
  def edit
    @shipping_info = ShippingInfo.find(params[:id])
  end

  # POST /shipping_infos
  # POST /shipping_infos.json
  def create
    @user = current_user
    @shipping_info = ShippingInfo.new(shipping_info_params)
    @user.shipping_info = @shipping_info
    
    respond_to do |format|
      if @shipping_info.save
        format.html { redirect_to "/users", notice: 'Shipping info was successfully created.' }
        format.json { render json: @shipping_info, status: :created, location: @shipping_info }
      else
        format.html { render action: "new" }
        format.json { render json: @shipping_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shipping_infos/1
  # PUT /shipping_infos/1.json
  def update
    @shipping_info = ShippingInfo.find(params[:id])

    respond_to do |format|
      if @shipping_info.update_attributes(shipping_info_params)
        format.html { redirect_to @shipping_info, notice: 'Shipping info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shipping_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_infos/1
  # DELETE /shipping_infos/1.json
  def destroy
    @shipping_info = ShippingInfo.find(params[:id])
    @shipping_info.destroy

    respond_to do |format|
      format.html { redirect_to shipping_infos_url }
      format.json { head :no_content }
    end
  end
  def shipping_info_params
    params.require(:shipping_info).permit(:first_name, :user_id, :last_name, :address, :city, :state, :country, :post_code, :phone)
  end
end

www/app/helpers/shipping_infos_helper.rb
module ShippingInfosHelper
end

www/app/views/shipping_infos/_form.html.slim
div class="progress progress-striped active"
  div class="bar" style="width: 60%;"

= simple_form_for(@shipping_info) do |f|
  br
  h4 Личные Данные
  = f.input :first_name,   placeholder: 'Имя',                  label: false
  = f.input :last_name,    placeholder: 'Фамилия',              label: false
  = f.input :address,      placeholder: 'Адресс',               label: false
  = f.input :city,         placeholder: 'Город',                label: false
  = f.input :state,        placeholder: 'Область',              label: false
  = f.input :country,      placeholder: 'Страна',               label: false
  = f.input :post_code,    placeholder: 'индекс',               label: false
  = f.input :phone,        placeholder: 'Контактный телефон',   label: false
  .control-group
    .controls
      = f.button :submit, 'Зарегистрировать'

www/app/views/shipping_infos/edit.html.slim
h1 Editing shipping_info

== render 'form'

= link_to 'Show', @shipping_info
'|
= link_to 'Back', shipping_infos_path

www/app/views/shipping_infos/index.html.slim
h1 Listing shipping_infos

table
  tr
    th
    th
    th

  - @shipping_infos.each do |shipping_info|
    tr
      td = link_to 'Show', shipping_info
      td = link_to 'Edit', edit_shipping_info_path(shipping_info)
      td = link_to 'Destroy', shipping_info, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Shipping info', new_shipping_info_path

www/app/views/shipping_infos/new.html.slim
h1 Регистрация

== render 'form'

= link_to 'Back', shipping_infos_path

www/app/views/shipping_infos/show.html.slim
p#notice = notice


= link_to 'Edit', edit_shipping_info_path(@shipping_info)
'|
= link_to 'Back', shipping_infos_path