www/config/routes.rb
Www::Application.routes.draw do

    

    get "home/index"

    resources :signin_or_signups

    resources :shipping_infos
    resources :make_a_choices

    get "sessions/new"
    get "cart/new"
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :product_categories do
        resources :products
    end
    resources :users do
        resources :carts
    end
    resources :users do
        resources :shipping_infos
    end
    resources :carts

    
    resources :product_providers

    get '/main',                  :to => 'product_categories#index'
    get '/signin',                :to => 'sessions#new'
    get '/signout',               :to => 'sessions#destroy'
    get '/signup',                :to => 'users#new'
    post '/add_product/:id',       :to => 'carts#new'
    post '/delete_product/:id',    :to => 'carts#destroy'
    get '/signup_step2',          :to => 'shipping_infos#new'
    get '/cart',                  :to => 'carts#show'
    get '/make_a_choice',         :to => 'make_a_choices#index'
    get '/update_qnt',            :to => 'carts#update' 

    root :to => "home#index"

end

www/app/models/product_provider.rb
class ProductProvider < ActiveRecord::Base
=begin
    attr_accessible :name
    attr_accessible :currency
    attr_accessible :active
=end
end

www/app/controllers/product_providers_controller.rb
class ProductProvidersController < ApplicationController
  # GET /product_providers
  # GET /product_providers.json
  def index
    @product_providers = ProductProvider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_providers }
    end
  end

  # GET /product_providers/1
  # GET /product_providers/1.json
  def show
    @product_provider = ProductProvider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_provider }
    end
  end

  # GET /product_providers/new
  # GET /product_providers/new.json
  def new
    @product_provider = ProductProvider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_provider }
    end
  end

  # GET /product_providers/1/edit
  def edit
    @product_provider = ProductProvider.find(params[:id])
  end

  # POST /product_providers
  # POST /product_providers.json
  def create
    @product_provider = ProductProvider.new(product_provider_params)

    respond_to do |format|
      if @product_provider.save
        format.html { redirect_to @product_provider, notice: 'Product provider was successfully created.' }
        format.json { render json: @product_provider, status: :created, location: @product_provider }
      else
        format.html { render action: "new" }
        format.json { render json: @product_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_providers/1
  # PUT /product_providers/1.json
  def update
    @product_provider = ProductProvider.find(params[:id])

    respond_to do |format|
      if @product_provider.update_attributes(product_provider_params)
        format.html { redirect_to @product_provider, notice: 'Product provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_providers/1
  # DELETE /product_providers/1.json
  def destroy
    @product_provider = ProductProvider.find(params[:id])
    @product_provider.destroy

    respond_to do |format|
      format.html { redirect_to product_providers_url }
      format.json { head :no_content }
    end
  end
  def product_provider_params
    params.require(:product_provider).permit(:name, :currency, :active)
  end
end

www/app/helpers/product_providers_helper.rb
module ProductProvidersHelper
end

www/app/views/product_providers/_form.html.slim
= simple_form_for(@product_provider) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

www/app/views/product_providers/edit.html.slim
h1 Editing product_provider

== render 'form'

= link_to 'Show', @product_provider
'|
= link_to 'Back', product_providers_path

www/app/views/product_providers/index.html.slim
h1 Listing product_providers

table
  tr
    th
    th
    th

  - @product_providers.each do |product_provider|
    tr
      td = link_to 'Show', product_provider
      td = link_to 'Edit', edit_product_provider_path(product_provider)
      td = link_to 'Destroy', product_provider, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Product provider', new_product_provider_path

www/app/views/product_providers/new.html.slim
h1 New product_provider

== render 'form'

= link_to 'Back', product_providers_path

www/app/views/product_providers/show.html.slim
p#notice = notice


= link_to 'Edit', edit_product_provider_path(@product_provider)
'|
= link_to 'Back', product_providers_path